language: node_js
node_js:
    - "node"

cache:
  directories:
    - node_modules

script:
  - ng build --prod --base-href https://emptyflash.github.io/allergeez/
  - cp dist/index.html dist/404.html

after_success:
  - ngh
