language: node_js
node_js:
    - "7"

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --output-path dist --base-href allergeez

after_success:
  - ngh --message="Deploying!"
