import { Component, Input } from '@angular/core';
import { AppProvider, Level } from '../../providers/app.provider';


@Component({
  selector: 'charts',
  templateUrl: './charts.component.html',
  styleUrls: ['./charts.component.less']
})
export class ChartsComponent {
  // for the charts, generated by http://vrl.cs.brown.edu/color
  colorScheme = {
    domain: ['#208eb7', '#c9197d', '#36e515', '#911dcb', '#87ba4b', '#6c2c76', '#f3c011', '#243d59', '#f2cdb9', '#155126', '#fe79ec', '#11e38c', '#7b0905', '#77d1fd', '#673d17', '#c7acf9', '#ed8220', '#315eea', '#f24219', '#fb899b']
  };

  constructor(private appService: AppProvider) {}
}
